[project]
name = "nero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "chromadb>=1.3.5",
    "mlx-lm>=0.28.4",
    "pandas>=2.3.3",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.50.0",
    "tqdm>=4.67.1",
]
